<?php
/**
 * Created by PhpStorm.
 * User: HiraldoTran
 * Date: 11/7/18
 * Time: 9:53 AM
 */

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $ticketId
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByIdJoinedToUsuario($ticketId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT t,ua,u FROM AppBundle:Ticket t
        JOIN t.usuarioAsignado ua JOIN t.usuario u
        WHERE t.usuario = :id or t.usuarioAsignado= :id'
            )->setParameter('id', $ticketId);

        try {
            return $query->getArrayResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }
}