<?php
/**
 * Created by PhpStorm.
 * User: HiraldoTran
 * Date: 11/7/18
 * Time: 9:53 AM
 */

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $role
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByRoleUsuario($role)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:Usuario u
        
        WHERE u.tipoUsuario = :tipo_usuario'
            )->setParameter('tipo_usuario', $role);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }

    /**
     * @param $role
     * @return null
     */
    public function findByRolesUsuario($role){
        $query=$this->findBy(['tipoUsuario' => $role]);
        try {
            return $query;
        } catch (\Doctrine\ORM\NoResultException $exception) {
            return null;
        }
    }
}