# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\Usuario:
        algorithm: bcrypt
        cost: 12

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
          entity:
            class: AppBundle:Usuario
            property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: db_provider
            form_login:
              login_path: /login
              check_path: /login
            logout:
              path: /logout
              target: /login
            access_denied_handler: AppBundle\Security\AccessDeniedHandler
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/rest/usuario, roles: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/rest/nota, roles: [ROLE_TECNICO,ROLE_NORMAL]}
            - { path: ^/task/crear, roles: ROLE_NORMAL}
            - { path: ^/task, roles: [ROLE_TECNICO,ROLE_NORMAL]}
            - { path: ^/pendiente, roles: ROLE_NORMAL}
            - { path: ^/proceso, roles: ROLE_NORMAL}
            - { path: ^/rest/task/, roles: [ROLE_TECNICO,ROLE_NORMAL]}
            - { path: ^/usuario, roles: ROLE_ADMIN}
            - { path: ^/, roles: [ROLE_TECNICO,ROLE_NORMAL]}

